### ISSUE TITLE
OMP to provide an IBM Cloud account to migrate galasa infrastructure to.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/TSC#15]

**Comment by techcobweb** [comment]
From the TSC meeting minutes : 

Currently the team have moved from the IBM internal cloud officially, however they have had to split the infrastructure in the meantime before we get official confirmation that we can move.
- Louisa to ask John Mertic what the latest is on the IBM Cloud provisioning.

**Comment by louisa-seers** [comment]
This has now been provided by John Mertic. Migrating is in progress.
