### ISSUE TITLE
Annual Review for Galasa - April 2024

### ISSUE THREAD

**Issue by louisa-seers** [galasa-dev/TSC#20]
As per this issue: https://github.com/openmainframeproject/tac/issues/584, Galasa has to have the annual review in April.

The guidance: https://tac.openmainframeproject.org/process/review_cycle

I have created a PPT and uploaded it here to keep track of the PPT: https://github.com/galasa-dev/TSC/blob/main/artifacts/Galasa-Annual-Review-April-2024.pptx

**Comment by louisa-seers** [comment]
Raised an issue with LFX Insights as they didn't have Galasa on their list. https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-25713

**Comment by louisa-seers** [comment]
[Galasa-Annual-Review-April-2024.pptx](https://github.com/galasa-dev/TSC/files/14915819/Galasa-Annual-Review-April-2024.pptx)


@hobbit1983 and @techcobweb - I'd appreciate you having a look over what I've done so far and whether you would have any comments or additions here.

**Comment by techcobweb** [comment]
## Slides 3: lol. You can spot when I joined the project and started work on the CLI in Sept/October 2022.

## Slide 6: 
> Fully Gherkin enabled"

I'm not convinced. We've not documented it very well yet I think. And I don't think our int tests run gherkin tests ? And only 6 managers support it. Putting it first gives Gherkin too much emphasis. It's not a great system to use compared to Java.

> Galasa now has a comprehensive CLI which has replaced the Eclipse plug-in – for example listing historical runs, downloading artifacts, cancelling tests, launching local tests.

You could add "creating example projects, logging in to a remote ecosystem,, manipulating CPS test and manager configuration parameters"
And "listing historical runs" could be "listing historical and active runs"

> Improving security and authentication in Galasa through HTTPS and dex authentication service

This is the main thing we've done. It's buried in the middle.
It includes:
- Use a new web UI to allocate personal access tokens
- Ports to internal services (etcd and couchdb) no longer accessible outside of the Kubernetes cluster.
- Rest authorisation API to swap personal access tokens with JWT access tokens
- All rest calls demand a JWT access token
- Authorise your CLI tool to talk to an ecosystem using an access token

**Comment by techcobweb** [comment]
> Restructuring documentation for the CLI ability through VS Code

This should probably de-emphasise VS code. The message is that the docs were restructured from the CLI viewpoint, using any IDE, or automation framework.

**Comment by techcobweb** [comment]
Good to show the roadmap, but that's way out of date, and not what we actually ended up doing...
Latest is here: https://ibm.box.com/s/d47s31lziipxk7yb3hhj7oznclha0k7d

**Comment by techcobweb** [comment]
> Feedback on working with the Open Mainframe Project
- Helpful. 
- Took a while to get a cloud account organised. Hope to move to it at some point soon.
- Security scans work, though problems remain about how to show current vs. historic results.

**Comment by louisa-seers** [comment]
Completed and PPT here: 

[Galasa-Annual-Review-April-2024.pptx](https://github.com/galasa-dev/TSC/files/15190060/Galasa-Annual-Review-April-2024.pptx)
