### ISSUE TITLE
17-10-2023 tsc meeting

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/TSC#4]
# Agenda
- Publicity
- Slack channel update
- Blockers
- Cluster infrastructure progress
- Whats in 0.30.0
- Whats planned in 0.31.0 
- How might we get a 3270 resource accessible from the IBM cloud to test our 3270 functionality against
- When can we deprecate and retire eclipse plugins for Galasa. Under what conditions could we do that ?

# Attendees
# Minutes

## Publicity
- GSE conference in 2 weeks
- Share submissions have gone
- GSE Nordics have 'come up' - live demo of creating tests from scratch needs adding. 
  - @hobbit1983 is investigating further.
- Publicity of the new `galasa properties get` functionality (new in 0.30.0).
  - Video introducing CPS

## Whats in the 0.30.0 release
Look in the KanBan board, there is a column "Done in this release". https://github.com/orgs/galasa-dev/projects/3/views/1

Release notes will be published on galasa.dev website, but summary:
- CLuster move
- Release of 0.30.0
- `galasactl properties get/set/delete` commands.

## OMP-owned cloud account
- PII questionaire
- @louisa-seers chasing up with John Mertec.

## Access to 3270 resource outside of the IBM firewall ?
- OMP may have access to a mainframe.
- First step @louisa-seers to talk to John Mertec to see if we can have any access.

## Question about should we deprecate/retire/remove eclipse plugins ?
- Lots of discussion on about this in the meeting (see transcript). eg: Reasons why we want to do this.
- What conditions which need to be met before we can think about this:
  - CLI to be able to pull 3270 images into files from tests run on ecosysyems
  - CLI ability to kill a running test
  - CLI ability to create an OBR project for projects which don't have one
- Add this to the agenda to the next TSC meeting

**Comment by techcobweb** [comment]
@louisa-seers I would like to add 2 items for discussion at the TSC meeting:
- Progress on OMP IBMCloud account for cluster migration to target
- How might we get a 3270 resource accessible from the IBM cloud to test our 3270 functionality against

**Comment by louisa-seers** [comment]
Added to main repo.

**Comment by techcobweb** [comment]
Meeting minutes now kept in files in the repo, not in issues.
