### ISSUE TITLE
Change to eclipse plugin

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/TSC#7]
we would like to discuss the future of the eclipse plugin within eclipse, potential removal and how that affects the project and community

**Comment by techcobweb** [comment]
Eclipse will be removed. See https://github.com/galasa-dev/TSC/blob/main/minutes/2023/2023-11-21-why-drop-eclipse.md and the meeting minutes https://github.com/galasa-dev/TSC/blob/main/minutes/2023/2023-11-21%20TSC%20Meeting%20Minutes.md
